dockersyslog:
  image: jmcarbo/docker-syslog:latest
  ports:
    - 55555:1514/udp
  environment:
    TAG_EXCLUDE_FILTER: dockersyslog_1

logspout:
  image: progrium/logspout
  ports:
    - 8000:8000
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  command: syslog://192.168.59.103:55555
#  command: rfc5424://192.168.59.103:55555
